name: Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 18
        cache: 'npm'
    - name: Run Lint
      run: |
        npm ci
        npm run lint

  analyze:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: "javascript"
    - name: Analyze CodeQL
      uses: github/codeql-action/analyze@v2

  transpile:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 18
        cache: 'npm'
    - name: Transpile Code
      run: |
        npm ci
        npm run build

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 18
        cache: 'npm'
    - name: Run Tests
      run: |
        npm ci
        npm run test

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: [lint, analyze, test, transpile]
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
    - name: Checkout Git
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 18
        cache: 'npm'
    - name: Deploy Node
      run: |
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        npm ci
        npm run deploy:frontend
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-backend:
    runs-on: ubuntu-latest
    needs: [lint, analyze, test, transpile]
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Checkout Git
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 18
        cache: 'npm'
    - name: Deploy Node
      run: |
        echo "DEPLOY BACKEND"